apiVersion: v1
kind: ConfigMap
metadata:
  name: attribute-status
  namespace: attribute-status
data:
  AttributeStatusTopicName: attribute-status
  AttributeStatusSubscriptionName: attribute-status-writer
  ServiceBusConnection__fullyQualifiedNamespace: REPLACE.servicebus.windows.net
  ServiceBusFullyQualifiedNamespace: REPLACE.servicebus.windows.net

  AttributeStatusTarget: tables
  AttributeStatusPartitionKeyField: siteId
  AttributeStatusRowKeyField: attributeId
  AttributeStatusMaxConcurrentCalls: "1"

  AttributeStatusTableServiceUri: https://REPLACE.table.core.windows.net
  AttributeStatusTableName: AttributeStatus
  AttributeStatusEncodeTableKeys: "false"

  AttributeStatusMongoDatabase: attributeStatus
  AttributeStatusMongoCollection: statuses

  AzureWebJobsStorage__blobServiceUri: https://REPLACE.blob.core.windows.net
  AzureWebJobsStorage__queueServiceUri: https://REPLACE.queue.core.windows.net
  AzureWebJobsStorage__tableServiceUri: https://REPLACE.table.core.windows.net
  FUNCTIONS_WORKER_RUNTIME: java
  HealthPort: "8080"
