apiVersion: v1
kind: Secret
metadata:
  name: message-writer-logic-app
  namespace: message-persistence-sample
type: Opaque
stringData:
  AzureWebJobsStorage: REPLACE_WITH_WORKFLOW_STORAGE_CONNECTION_STRING
  APPLICATIONINSIGHTS_CONNECTION_STRING: REPLACE_WITH_APPLICATION_INSIGHTS_CONNECTION_STRING
  serviceBus_connectionString: REPLACE_WITH_LISTEN_CONNECTION_STRING
  tableStorage_connectionString: REPLACE_WITH_TABLE_STORAGE_CONNECTION_STRING
  kedaServiceBusConnectionString: REPLACE_WITH_MANAGE_CONNECTION_STRING
