apiVersion: v1
kind: ServiceAccount
metadata:
  name: message-writer
  namespace: message-persistence-sample
  annotations:
    azure.workload.identity/client-id: REPLACE_WITH_MANAGED_IDENTITY_CLIENT_ID
